### ISSUE TITLE
Remember video settings

### ISSUE THREAD

**Issue by Richard-L** [stohrendorf/EdisonEngine#129]
Currently disabling of post-processing like the CRT effect etc, as well as fullscreen mode, are not remembered.

**Comment by stohrendorf** [comment]
Can't reproduce this. On shutdown, the engine writes a `config.yaml` in the root directory where the .exe resides with the current settings, which should also be loaded on next startup. Can you confirm this file exists and contains something looking like this, only different in the numbers?

```yaml
config:
  renderSettings:
    crt: 1
    dof: 1
    lensDistortion: 1
    filmGrain: 1
    fullscreen: 1
```
